-- 创建用户菜单访问权限表
-- 用于控制用户能够访问哪些功能模块的菜单

-- 创建表
CREATE TABLE IF NOT EXISTS user_menu_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    menu_feature_id VARCHAR(100) NOT NULL,
    enabled BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, menu_feature_id)
);

-- 添加注释
COMMENT ON TABLE user_menu_access IS '用户菜单访问权限表';
COMMENT ON COLUMN user_menu_access.user_id IS '用户ID';
COMMENT ON COLUMN user_menu_access.menu_feature_id IS '菜单功能ID（对应MENU_FEATURES中的id）';
COMMENT ON COLUMN user_menu_access.enabled IS '是否启用';

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_user_menu_access_user_id ON user_menu_access(user_id);
CREATE INDEX IF NOT EXISTS idx_user_menu_access_menu_feature_id ON user_menu_access(menu_feature_id);

-- 创建更新时间触发器
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_user_menu_access_updated_at
    BEFORE UPDATE ON user_menu_access
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

-- 为所有管理员用户添加所有菜单权限
INSERT INTO user_menu_access (user_id, menu_feature_id, enabled)
SELECT 
    up.id,
    mf.menu_id,
    true
FROM user_profiles up
CROSS JOIN (
    VALUES 
        ('dashboard'),
        ('course_management'),
        ('training_management'),
        ('sales_tracking'),
        ('salesperson_management'),
        ('customer_management'),
        ('expert_management'),
        ('prospectus_management'),
        ('poster_generator'),
        ('announcement_management'),
        ('permission_management'),
        ('audit_logs'),
        ('profile_settings')
) AS mf(menu_id)
WHERE up.role = 'admin'
ON CONFLICT (user_id, menu_feature_id) DO NOTHING;

-- 为业务员用户添加默认菜单权限
INSERT INTO user_menu_access (user_id, menu_feature_id, enabled)
SELECT 
    up.id,
    mf.menu_id,
    true
FROM user_profiles up
CROSS JOIN (
    VALUES 
        ('dashboard'),
        ('course_management'),
        ('training_management'),
        ('customer_management'),
        ('prospectus_management'),
        ('profile_settings')
) AS mf(menu_id)
WHERE up.role = 'salesperson'
ON CONFLICT (user_id, menu_feature_id) DO NOTHING;

-- 为专家用户添加默认菜单权限
INSERT INTO user_menu_access (user_id, menu_feature_id, enabled)
SELECT 
    up.id,
    mf.menu_id,
    true
FROM user_profiles up
CROSS JOIN (
    VALUES 
        ('dashboard'),
        ('training_management'),
        ('expert_management'),
        ('prospectus_management'),
        ('profile_settings')
) AS mf(menu_id)
WHERE up.role = 'expert'
ON CONFLICT (user_id, menu_feature_id) DO NOTHING;

-- 为部门经理用户添加默认菜单权限
INSERT INTO user_menu_access (user_id, menu_feature_id, enabled)
SELECT 
    up.id,
    mf.menu_id,
    true
FROM user_profiles up
CROSS JOIN (
    VALUES 
        ('dashboard'),
        ('course_management'),
        ('training_management'),
        ('sales_tracking'),
        ('salesperson_management'),
        ('customer_management'),
        ('expert_management'),
        ('prospectus_management'),
        ('poster_generator'),
        ('profile_settings')
) AS mf(menu_id)
WHERE up.role = 'manager'
ON CONFLICT (user_id, menu_feature_id) DO NOTHING;

-- 创建RLS策略
ALTER TABLE user_menu_access ENABLE ROW LEVEL SECURITY;

-- 策略：用户可以查看自己的菜单权限
CREATE POLICY "Users can view own menu access" ON user_menu_access
    FOR SELECT
    USING (auth.uid() = user_id);

-- 策略：管理员可以管理所有用户的菜单权限
CREATE POLICY "Admins can manage all menu access" ON user_menu_access
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM user_profiles
            WHERE user_profiles.id = auth.uid()
            AND user_profiles.role = 'admin'
        )
    );

-- 查看结果
SELECT 
    up.name,
    up.role,
    COUNT(uma.menu_feature_id) as menu_count,
    STRING_AGG(uma.menu_feature_id, ', ' ORDER BY uma.menu_feature_id) as menus
FROM user_profiles up
LEFT JOIN user_menu_access uma ON up.id = uma.user_id AND uma.enabled = true
GROUP BY up.id, up.name, up.role
ORDER BY up.role, up.name;
